//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassLog
    {
        public int Id { get; set; }
        public int PassId { get; set; }
        public bool IsEnter { get; set; }
        public System.DateTime DateTime { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Pass Pass { get; set; }
    }
}
